cart/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.cart, name="cart"),
    path("remove/<int:cart_item_id>/", views.remove, name="remove"),
    path("checkout", views.checkout, name="checkout"),
    path("mark_complete/<int:order_item_id>/", views.mark_complete, name="mark_complete")
]

orders/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("get_price", views.get_price, name="get_price")
]

pizza/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("orders.urls")),
    path("cart/", include("cart.urls")),
    path("accounts/", include("accounts.urls")),
    path("admin/", admin.site.urls),
]

orders/models.py
from django.db import models


class Menu(models.Model):
    name = models.CharField(max_length=16, blank=False)

    def __str__(self):
        return f"{self.name}"


class Size(models.Model):
    name = models.CharField(max_length=16, blank=False)

    def __str__(self):
        return self.name


class PizzaStyle(models.Model):
    name = models.CharField(max_length=16, blank=False)

    def __str__(self):
        return self.name


class Topping(models.Model):
    name = models.CharField(max_length=64)

    def __str__(self):
        return self.name


class Ingredient(models.Model):
    name = models.CharField(max_length=64)

    def __str__(self):
        return self.name


class Extra(models.Model):
    name = models.CharField(max_length=64)
    added_cost = models.DecimalField(max_digits=5, default=0.50, decimal_places=2)

    def __str__(self):
        return f"{self.name}"


class PastaStyle(models.Model):
    name = models.CharField(max_length=64)

    def __str__(self):
        return self.name


class SaladStyle(models.Model):
    name = models.CharField(max_length=64)

    def __str__(self):
        return self.name


class DinnerPlatterStyle(models.Model):
    name = models.CharField(max_length=64)

    def __str__(self):
        return self.name


class Pizza(models.Model):
    menu = models.ForeignKey(Menu, on_delete=models.CASCADE, related_name="pizza")
    style = models.ForeignKey(PizzaStyle, on_delete=models.CASCADE)
    size = models.ForeignKey(Size, on_delete=models.CASCADE)
    is_special = models.BooleanField(default=False)
    toppings = models.ManyToManyField(Topping, blank=True)
    num_toppings = models.IntegerField()
    price = models.DecimalField(max_digits=5, default=0.00, decimal_places=2)

    def toppings_list(self):
        return "\n".join([p.name for p in self.toppings.all()])

    def special(self):
        if self.is_special:
            return "Yes"
        else:
            return "No"

    def __str__(self):
        return f"{self.menu}: {self.style} | {self.size} | Special?: {self.special()} | "


class Sub(models.Model):
    menu = models.ForeignKey(Menu, on_delete=models.CASCADE, related_name="sub")
    ingredients = models.ForeignKey(Ingredient, blank=False, on_delete=models.CASCADE)
    size = models.ForeignKey(Size, on_delete=models.CASCADE)
    extras = models.ManyToManyField(Extra, blank=True)
    price = models.DecimalField(max_digits=5, default=0.00, decimal_places=2)

    def extras_list(self):
        query_set = self.extras.all()
        if not query_set:
            return "No extras"
        else:
            return "\n".join([p.name for p in query_set])

    def __str__(self):
        extras = self.extras_list()
        return f"{self.menu}: {self.ingredients} | {self.size} | {self.price} | Extras: {extras}"


class Pasta(models.Model):
    menu = models.ForeignKey(Menu, on_delete=models.CASCADE, related_name="pasta")
    style = models.ForeignKey(PastaStyle, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=5, default=0.00, decimal_places=2)

    def __str__(self):
        return f"{self.menu} | {self.style} | {self.price}"


class Salad(models.Model):
    menu = models.ForeignKey(Menu, on_delete=models.CASCADE, related_name="salad")
    style = models.ForeignKey(SaladStyle, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=5, default=0.00, decimal_places=2)

    def __str__(self):
        return f"{self.menu} | {self.style} | {self.price}"


class DinnerPlatter(models.Model):
    menu = models.ForeignKey(Menu, on_delete=models.CASCADE, related_name="dinner_platter")
    style = models.ForeignKey(DinnerPlatterStyle, on_delete=models.CASCADE)
    size = models.ForeignKey(Size, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=5, default=0.00, decimal_places=2)

    def __str__(self):
        return f"{self.menu} | {self.style} | {self.price}"

orders/forms.py
from django.forms import ModelForm, CheckboxSelectMultiple
from .models import Pizza, Sub, Pasta, Salad, DinnerPlatter


class PizzaForm(ModelForm):
    class Meta:
        model = Pizza
        exclude = ['menu', 'price']
        widgets = {
            'toppings': CheckboxSelectMultiple,
        }
        labels = {
            'num_toppings': 'Number of Toppings',
            'is_special': 'Gluten Free Dough'
        }


class SubForm(ModelForm):
    class Meta:
        model = Sub
        exclude = ['menu', 'price']
        widgets = {
            'extras': CheckboxSelectMultiple,
        }
        labels = {
            'ingredients': 'Ingredients'
        }


class PastaForm(ModelForm):
    class Meta:
        model = Pasta
        exclude = ['menu', 'price']


class SaladForm(ModelForm):
    class Meta:
        model = Salad
        exclude = ['menu', 'price']


class DinnerPlatterForm(ModelForm):
    class Meta:
        model = DinnerPlatter
        exclude = ['menu', 'price']

orders/views.py
from django.shortcuts import render, redirect
from .forms import PizzaForm, SubForm, PastaForm, SaladForm, DinnerPlatterForm
from .models import Pizza, Sub, Pasta, Salad, DinnerPlatter
from cart.views import get_cart_items
from django.http import JsonResponse
from decimal import Decimal


def index(request):

    if request.user.is_authenticated:

        data = {
            'Pizza': PizzaForm(),
            'Sub': SubForm(),
            'Pasta': PastaForm(),
            'Salad': SaladForm(),
            'DinnerPlatter': DinnerPlatterForm()
            }

        cart_items = get_cart_items(request)

        context = {
            'data': data,
            'num_cart_items': cart_items.count()

        }
        return render(request, 'orders/index.html', context)
    else:
        return redirect('login')


def get_price(request):
    menu_item = request.GET.get('menu_item')
    price = "--.--"
    if menu_item == 'Pizza':
        style = request.GET.get('style')
        size = request.GET.get('size')
        num_toppings = request.GET.get('num_toppings')
        is_special = request.GET.get('is_special')
        if is_special == 'true':
            is_special = True
        else:
            is_special = False

        if style != "" and size != "" and num_toppings != "":
            if is_special:
                # numtoppings doesn't matter
                menu_pizza = Pizza.objects.get(style=style, size=size, is_special=is_special)
            else:
                menu_pizza = Pizza.objects.get(style=style, size=size, num_toppings=num_toppings, is_special=is_special)
            price = menu_pizza.price
    elif menu_item == 'Sub':
        ingredients = request.GET.get('ingredients')
        size = request.GET.get('size')
        extras = request.GET.get('extras')
        menu_sub = Sub.objects.get(ingredients=ingredients, size=size)
        price = menu_sub.price + Decimal(0.50)*int(extras)
    elif menu_item == 'Pasta':
        style = request.GET.get('style')
        menu_pasta = Pasta.objects.get(style=style)
        price = menu_pasta.price
    elif menu_item == 'Salad':
        style = request.GET.get('style')
        menu_salad = Salad.objects.get(style=style)
        price = menu_salad.price
    elif menu_item == 'DinnerPlatter':
        style = request.GET.get('style')
        size = request.GET.get('size')
        if style != "" and size != "":
            menu_dinner_platter = DinnerPlatter.objects.get(style=style, size=size)
            price = menu_dinner_platter.price
    else:
        price = "--.--"
    data = {
        'price': price
    }
    return JsonResponse(data)

templates/orders/index.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}

{% for title, form in data.items %}

<h1>{{ title }}</h1>

<form action="{% url 'cart' %}" method="post" id="{{ title }}">
    {% csrf_token %}
    <input type="hidden" value="{{ title }}" name="menu_item" id="menu_item" />

    {{ form | crispy }}

    <h5 id='price_indicator'>Price: $--.--</h5>
    <input type="submit" value="Add {{ title }} to Cart" />
</form>
<br><br><br>

{% endfor %}

{% endblock %}

{% block javascript %}
<script>
    $(document).ready(function() {

        $('#Pizza').change(function() {
            var menu_item = $('#Pizza #menu_item').val();
            var style = $('#Pizza #id_style option:selected').val();
            var size = $('#Pizza #id_size option:selected').val();
            var is_special = $('#Pizza #id_is_special').is(':checked');
            var last_checked = $("#Pizza #id_toppings input[name='toppings']:checked").val();
            var num_checked = $("input[name='toppings']:checked").length;
            var limit = 3;

            $('#Pizza #id_num_toppings').val(num_checked);

            if (num_checked > limit) {
                alert("You can only select up to 3 toppings!");
                $("input[name='toppings']").prop('checked', false);
                $('#Pizza #id_num_toppings').val('0');
            }
            var num_toppings = $('#Pizza #id_num_toppings').val();
            $.ajax({
                type: "GET",
                url: '{% url "get_price" %}',
                data: {
                    'menu_item': menu_item,
                    'style': style,
                    'size': size,
                    'num_toppings': num_toppings,
                    'is_special': is_special,
                },
                dataType: 'json',
                success: function(data) {
                    var x = data['price'];
                    $('#Pizza #price_indicator').html("Price: $" + x);
                }

            });
        });
        $('#Sub').change(function() {
            var menu_item = $('#Sub #menu_item').val();
            var ingredients = $('#Sub #id_ingredients option:selected').val();
            var size = $('#Sub #id_size option:selected').val();
            var extras = $("input[name='extras']:checked").length;

            // Cannot have a Small Sausage, Peppers, Onions edge case
            if (ingredients == 11 && size == 1) {
                alert("This option is only available in Large Size!");
                $('#Sub #id_size option[value=2]').attr('selected', 'selected');
            }

            $.ajax({
                type: "GET",
                url: '{% url "get_price" %}',
                data: {
                    'menu_item': menu_item,
                    'ingredients': ingredients,
                    'size': size,
                    'extras': extras,
                },
                dataType: 'json',
                success: function(data) {
                    var x = data['price'];
                    $('#Sub #price_indicator').html("Price: $" + x);
                }

            });
        });
        $('#Pasta').change(function() {
            var menu_item = $('#Pasta #menu_item').val();
            var style = $('#Pasta #id_style option:selected').val();

            $.ajax({
                type: "GET",
                url: '{% url "get_price" %}',
                data: {
                    'menu_item': menu_item,
                    'style': style,
                },
                dataType: 'json',
                success: function(data) {
                    var x = data['price'];
                    $('#Pasta #price_indicator').html("Price: $" + x);
                }

            });
        });
        $('#Salad').change(function() {
            var menu_item = $('#Salad #menu_item').val();
            var style = $('#Salad #id_style option:selected').val();

            $.ajax({
                type: "GET",
                url: '{% url "get_price" %}',
                data: {
                    'menu_item': menu_item,
                    'style': style,
                },
                dataType: 'json',
                success: function(data) {
                    var x = data['price'];
                    $('#Salad #price_indicator').html("Price: $" + x);
                }

            });
        });
        $('#DinnerPlatter').change(function() {
            var menu_item = $('#DinnerPlatter #menu_item').val();
            var style = $('#DinnerPlatter #id_style option:selected').val();
            var size = $('#DinnerPlatter #id_size option:selected').val();

            $.ajax({
                type: "GET",
                url: '{% url "get_price" %}',
                data: {
                    'menu_item': menu_item,
                    'style': style,
                    'size': size,
                },
                dataType: 'json',
                success: function(data) {
                    var x = data['price'];
                    $('#DinnerPlatter #price_indicator').html("Price: $" + x);
                }

            });
        });
    });
</script>
{% endblock %}